[2023-11-26T23:19:00.282+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=outcomes_dag/run_id=manual__2023-11-26T23:18:15.063757+00:00/task_id=load permission to 509
[2023-11-26T23:19:00.321+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=outcomes_dag/run_id=manual__2023-11-26T23:18:15.063757+00:00/task_id=load permission to 509
[2023-11-26T23:19:00.604+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.load manual__2023-11-26T23:18:15.063757+00:00 [queued]>
[2023-11-26T23:19:00.616+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.load manual__2023-11-26T23:18:15.063757+00:00 [queued]>
[2023-11-26T23:19:00.618+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-26T23:19:00.634+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load> on 2023-11-26 23:18:15.063757+00:00
[2023-11-26T23:19:00.643+0000] {standard_task_runner.py:57} INFO - Started process 376 to run task
[2023-11-26T23:19:00.646+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'load', 'manual__2023-11-26T23:18:15.063757+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpmyftwmz6']
[2023-11-26T23:19:00.648+0000] {standard_task_runner.py:85} INFO - Job 34: Subtask load
[2023-11-26T23:19:00.699+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=outcomes_dag/run_id=manual__2023-11-26T23:18:15.063757+00:00/task_id=load permission to 509
[2023-11-26T23:19:00.702+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.load manual__2023-11-26T23:18:15.063757+00:00 [running]> on host 613ffde293d8
[2023-11-26T23:19:00.798+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2023-11-26T23:18:15.063757+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-26T23:18:15.063757+00:00'
[2023-11-26T23:19:00.800+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: load_data() missing 3 required positional arguments: 'gcs_bucket', 'blob_name', and 'creds'
[2023-11-26T23:19:00.810+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=load, execution_date=20231126T231815, start_date=20231126T231900, end_date=20231126T231900
[2023-11-26T23:19:00.823+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 34 for task load (load_data() missing 3 required positional arguments: 'gcs_bucket', 'blob_name', and 'creds'; 376)
[2023-11-26T23:19:00.859+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-26T23:19:00.878+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
