[2023-11-25T18:51:29.281+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=outcomes_dag/run_id=scheduled__2023-11-08T00:00:00+00:00/task_id=extract permission to 509
[2023-11-25T18:51:29.853+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=outcomes_dag/run_id=scheduled__2023-11-08T00:00:00+00:00/task_id=extract permission to 509
[2023-11-25T18:51:29.916+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.extract scheduled__2023-11-08T00:00:00+00:00 [queued]>
[2023-11-25T18:51:29.936+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.extract scheduled__2023-11-08T00:00:00+00:00 [queued]>
[2023-11-25T18:51:29.938+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-25T18:51:29.981+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): extract> on 2023-11-08 00:00:00+00:00
[2023-11-25T18:51:30.021+0000] {standard_task_runner.py:57} INFO - Started process 102 to run task
[2023-11-25T18:51:30.431+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'extract', 'scheduled__2023-11-08T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpgayr467f']
[2023-11-25T18:51:30.440+0000] {standard_task_runner.py:85} INFO - Job 11: Subtask extract
[2023-11-25T18:51:31.199+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=outcomes_dag/run_id=scheduled__2023-11-08T00:00:00+00:00/task_id=extract permission to 509
[2023-11-25T18:51:31.204+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.extract scheduled__2023-11-08T00:00:00+00:00 [running]> on host 533b0beedf51
[2023-11-25T18:51:34.448+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2023-11-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-08T00:00:00+00:00'
[2023-11-25T18:51:34.459+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-25T18:51:34.461+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl --create-dirs -o /opt/***/data/2023-11-08/downloads/outcomes_2023-11-08.csv https://data.austintexas.gov/api/views/9t4d-g238/rows.csv']
[2023-11-25T18:51:34.502+0000] {subprocess.py:86} INFO - Output:
[2023-11-25T18:51:34.540+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2023-11-25T18:51:34.542+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2023-11-25T18:51:42.796+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100 2254k    0 2254k    0     0  1495k      0 --:--:--  0:00:01 --:--:-- 1495k100 5006k    0 5006k    0     0  1996k      0 --:--:--  0:00:02 --:--:-- 1995k100 7102k    0 7102k    0     0  1895k      0 --:--:--  0:00:03 --:--:-- 1894k100 9485k    0 9485k    0     0  2104k      0 --:--:--  0:00:04 --:--:-- 2104k100 11.4M    0 11.4M    0     0  2104k      0 --:--:--  0:00:05 --:--:-- 2323k100 14.0M    0 14.0M    0     0  2214k      0 --:--:--  0:00:06 --:--:-- 2431k100 16.6M    0 16.6M    0     0  2268k      0 --:--:--  0:00:07 --:--:-- 2406k100 19.0M    0 19.0M    0     0  2360k      0 --:--:--  0:00:08 --:--:-- 2746k
[2023-11-25T18:51:42.801+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-11-25T18:51:42.870+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=extract, execution_date=20231108T000000, start_date=20231125T185129, end_date=20231125T185142
[2023-11-25T18:51:42.946+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-25T18:51:43.006+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-11-25T19:43:23.509+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=outcomes_dag/run_id=scheduled__2023-11-08T00:00:00+00:00/task_id=extract permission to 509
[2023-11-25T19:43:23.591+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=outcomes_dag/run_id=scheduled__2023-11-08T00:00:00+00:00/task_id=extract permission to 509
[2023-11-25T19:43:23.710+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.extract scheduled__2023-11-08T00:00:00+00:00 [queued]>
[2023-11-25T19:43:23.733+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.extract scheduled__2023-11-08T00:00:00+00:00 [queued]>
[2023-11-25T19:43:23.734+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-25T19:43:23.896+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): extract> on 2023-11-08 00:00:00+00:00
[2023-11-25T19:43:23.920+0000] {standard_task_runner.py:57} INFO - Started process 110 to run task
[2023-11-25T19:43:23.936+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'extract', 'scheduled__2023-11-08T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmplzghqn4s']
[2023-11-25T19:43:23.946+0000] {standard_task_runner.py:85} INFO - Job 11: Subtask extract
[2023-11-25T19:43:24.100+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=outcomes_dag/run_id=scheduled__2023-11-08T00:00:00+00:00/task_id=extract permission to 509
[2023-11-25T19:43:24.107+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.extract scheduled__2023-11-08T00:00:00+00:00 [running]> on host a66846cad9d1
[2023-11-25T19:43:24.649+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2023-11-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-08T00:00:00+00:00'
[2023-11-25T19:43:24.653+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-25T19:43:24.655+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl --create-dirs -o /opt/***/data/2023-11-08/downloads/outcomes_2023-11-08.csv https://data.austintexas.gov/api/views/9t4d-g238/rows.csv']
[2023-11-25T19:43:24.679+0000] {subprocess.py:86} INFO - Output:
[2023-11-25T19:43:24.699+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2023-11-25T19:43:24.700+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2023-11-25T19:44:04.942+0000] {job.py:219} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/jobs/job.py", line 190, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/future/engine.py", line 406, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-25T19:44:08.896+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100  207k    0  207k    0     0   142k      0 --:--:--  0:00:01 --:--:--  142k100  639k    0  639k    0     0   256k      0 --:--:--  0:00:02 --:--:--  256k100 1390k    0 1390k    0     0   410k      0 --:--:--  0:00:03 --:--:--  410k100 1790k    0 1790k    0     0   399k      0 --:--:--  0:00:04 --:--:--  399k100 2302k    0 2302k    0     0   406k      0 --:--:--  0:00:05 --:--:--  487k100 2846k    0 2846k    0     0   447k      0 --:--:--  0:00:06 --:--:--  537k100 3502k    0 3502k    0     0   461k      0 --:--:--  0:00:07 --:--:--  561k100 3902k    0 3902k    0     0   456k      0 --:--:--  0:00:08 --:--:--  486k100 4302k    0 4302k    0     0   450k      0 --:--:--  0:00:09 --:--:--  495k100 4670k    0 4670k    0     0   439k      0 --:--:--  0:00:10 --:--:--  476k100 4958k    0 4958k    0     0   435k      0 --:--:--  0:00:11 --:--:--  419k100 5310k    0 5310k    0     0   424k      0 --:--:--  0:00:12 --:--:--  366k100 5710k    0 5710k    0     0   425k      0 --:--:--  0:00:13 --:--:--  372k100 6110k    0 6110k    0     0   425k      0 --:--:--  0:00:14 --:--:--  375k100 6510k    0 6510k    0     0   422k      0 --:--:--  0:00:15 --:--:--  384k100 6990k    0 6990k    0     0   427k      0 --:--:--  0:00:16 --:--:--  408k100 7310k    0 7310k    0     0   419k      0 --:--:--  0:00:17 --:--:--  406k100 8222k    0 8222k    0     0   444k      0 --:--:--  0:00:18 --:--:--  494k100 8733k    0 8733k    0     0   445k      0 --:--:--  0:00:19 --:--:--  502k100 9101k    0 9101k    0     0   446k      0 --:--:--  0:00:20 --:--:--  523k100 9517k    0 9517k    0     0   442k      0 --:--:--  0:00:21 --:--:--  489k100 9757k    0 9757k    0     0   435k      0 --:--:--  0:00:22 --:--:--  491k100  9.9M    0  9.9M    0     0   434k      0 --:--:--  0:00:23 --:--:--  393k100 10.0M    0 10.0M    0     0   400k      0 --:--:--  0:00:25 --:--:--  256k100 10.0M    0 10.0M    0     0   384k      0 --:--:--  0:00:26 --:--:--  187k100 11.4M    0 11.4M    0     0   426k      0 --:--:--  0:00:27 --:--:--  371k100 11.7M    0 11.7M    0     0   417k      0 --:--:--  0:00:28 --:--:--  352k100 11.7M    0 11.7M    0     0   400k      0 --:--:--  0:00:29 --:--:--  280k100 11.7M    0 11.7M    0     0   383k      0 --:--:--  0:00:31 --:--:--  303k100 11.7M    0 11.7M    0     0   374k      0 --:--:--  0:00:32 --:--:--  324k100 11.7M    0 11.7M    0     0   341k      0 --:--:--  0:00:35 --:--:-- 36476100 11.7M    0 11.7M    0     0   334k      0 --:--:--  0:00:35 --:--:--     0100 11.7M    0 11.7M    0     0   291k      0 --:--:--  0:00:41 --:--:--     0100 12.4M    0 12.4M    0     0   307k      0 --:--:--  0:00:41 --:--:-- 73256100 16.0M    0 16.0M    0     0   388k      0 --:--:--  0:00:42 --:--:--  433k100 18.4M    0 18.4M    0     0   435k      0 --:--:--  0:00:43 --:--:--  833k100 19.0M    0 19.0M    0     0   441k      0 --:--:--  0:00:44 --:--:--  899k
[2023-11-25T19:44:08.924+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-11-25T19:44:09.074+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=extract, execution_date=20231108T000000, start_date=20231125T194323, end_date=20231125T194409
[2023-11-25T19:44:09.188+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-25T19:44:09.411+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-11-26T23:08:51.199+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=outcomes_dag/run_id=scheduled__2023-11-08T00:00:00+00:00/task_id=extract permission to 509
[2023-11-26T23:08:51.308+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=outcomes_dag/run_id=scheduled__2023-11-08T00:00:00+00:00/task_id=extract permission to 509
[2023-11-26T23:08:51.428+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.extract scheduled__2023-11-08T00:00:00+00:00 [queued]>
[2023-11-26T23:08:51.464+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.extract scheduled__2023-11-08T00:00:00+00:00 [queued]>
[2023-11-26T23:08:51.472+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-26T23:08:52.948+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract> on 2023-11-08 00:00:00+00:00
[2023-11-26T23:08:52.974+0000] {standard_task_runner.py:57} INFO - Started process 129 to run task
[2023-11-26T23:08:52.985+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'extract', 'scheduled__2023-11-08T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmp2hsn_vqg']
[2023-11-26T23:08:53.001+0000] {standard_task_runner.py:85} INFO - Job 11: Subtask extract
[2023-11-26T23:08:53.211+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=outcomes_dag/run_id=scheduled__2023-11-08T00:00:00+00:00/task_id=extract permission to 509
[2023-11-26T23:08:53.218+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.extract scheduled__2023-11-08T00:00:00+00:00 [running]> on host 613ffde293d8
[2023-11-26T23:08:53.400+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2023-11-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-08T00:00:00+00:00'
[2023-11-26T23:08:53.405+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: extract_data() missing 3 required positional arguments: 'source_url', 'gcs_bucket', and 'creds'
[2023-11-26T23:08:53.422+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=extract, execution_date=20231108T000000, start_date=20231126T230851, end_date=20231126T230853
[2023-11-26T23:08:53.457+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 11 for task extract (extract_data() missing 3 required positional arguments: 'source_url', 'gcs_bucket', and 'creds'; 129)
[2023-11-26T23:08:53.492+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-26T23:08:53.680+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
