[2023-11-25T18:51:30.809+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=outcomes_dag/run_id=scheduled__2023-11-10T00:00:00+00:00/task_id=extract permission to 509
[2023-11-25T18:51:31.106+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=outcomes_dag/run_id=scheduled__2023-11-10T00:00:00+00:00/task_id=extract permission to 509
[2023-11-25T18:51:31.201+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.extract scheduled__2023-11-10T00:00:00+00:00 [queued]>
[2023-11-25T18:51:31.221+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.extract scheduled__2023-11-10T00:00:00+00:00 [queued]>
[2023-11-25T18:51:31.224+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-25T18:51:31.276+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): extract> on 2023-11-10 00:00:00+00:00
[2023-11-25T18:51:31.289+0000] {standard_task_runner.py:57} INFO - Started process 119 to run task
[2023-11-25T18:51:31.785+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'extract', 'scheduled__2023-11-10T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpstb2u88e']
[2023-11-25T18:51:32.430+0000] {standard_task_runner.py:85} INFO - Job 13: Subtask extract
[2023-11-25T18:51:33.774+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=outcomes_dag/run_id=scheduled__2023-11-10T00:00:00+00:00/task_id=extract permission to 509
[2023-11-25T18:51:33.779+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.extract scheduled__2023-11-10T00:00:00+00:00 [running]> on host 533b0beedf51
[2023-11-25T18:51:35.298+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2023-11-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-10T00:00:00+00:00'
[2023-11-25T18:51:35.309+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-25T18:51:35.313+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl --create-dirs -o /opt/***/data/2023-11-10/downloads/outcomes_2023-11-10.csv https://data.austintexas.gov/api/views/9t4d-g238/rows.csv']
[2023-11-25T18:51:35.379+0000] {subprocess.py:86} INFO - Output:
[2023-11-25T18:51:35.410+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2023-11-25T18:51:35.411+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2023-11-25T18:51:43.266+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100  975k    0  975k    0     0   594k      0 --:--:--  0:00:01 --:--:--  594k100 3022k    0 3022k    0     0  1127k      0 --:--:--  0:00:02 --:--:-- 1126k100 6142k    0 6142k    0     0  1687k      0 --:--:--  0:00:03 --:--:-- 1687k100 8909k    0 8909k    0     0  1920k      0 --:--:--  0:00:04 --:--:-- 1919k100 11.4M    0 11.4M    0     0  2070k      0 --:--:--  0:00:05 --:--:-- 2369k100 13.9M    0 13.9M    0     0  2156k      0 --:--:--  0:00:06 --:--:-- 2668k100 17.9M    0 17.9M    0     0  2408k      0 --:--:--  0:00:07 --:--:-- 3101k100 19.0M    0 19.0M    0     0  2480k      0 --:--:--  0:00:07 --:--:-- 3163k
[2023-11-25T18:51:43.270+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-11-25T18:51:43.327+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=extract, execution_date=20231110T000000, start_date=20231125T185131, end_date=20231125T185143
[2023-11-25T18:51:43.424+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-25T18:51:43.500+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-11-25T19:43:24.263+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=outcomes_dag/run_id=scheduled__2023-11-10T00:00:00+00:00/task_id=extract permission to 509
[2023-11-25T19:43:24.314+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=outcomes_dag/run_id=scheduled__2023-11-10T00:00:00+00:00/task_id=extract permission to 509
[2023-11-25T19:43:24.386+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.extract scheduled__2023-11-10T00:00:00+00:00 [queued]>
[2023-11-25T19:43:24.405+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.extract scheduled__2023-11-10T00:00:00+00:00 [queued]>
[2023-11-25T19:43:24.406+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-25T19:43:24.441+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): extract> on 2023-11-10 00:00:00+00:00
[2023-11-25T19:43:24.458+0000] {standard_task_runner.py:57} INFO - Started process 128 to run task
[2023-11-25T19:43:24.464+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'extract', 'scheduled__2023-11-10T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmp1wznk3mm']
[2023-11-25T19:43:24.472+0000] {standard_task_runner.py:85} INFO - Job 13: Subtask extract
[2023-11-25T19:43:24.588+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=outcomes_dag/run_id=scheduled__2023-11-10T00:00:00+00:00/task_id=extract permission to 509
[2023-11-25T19:43:24.592+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.extract scheduled__2023-11-10T00:00:00+00:00 [running]> on host a66846cad9d1
[2023-11-25T19:43:25.072+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2023-11-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-10T00:00:00+00:00'
[2023-11-25T19:43:25.077+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-25T19:43:25.080+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl --create-dirs -o /opt/***/data/2023-11-10/downloads/outcomes_2023-11-10.csv https://data.austintexas.gov/api/views/9t4d-g238/rows.csv']
[2023-11-25T19:43:25.104+0000] {subprocess.py:86} INFO - Output:
[2023-11-25T19:43:25.122+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2023-11-25T19:43:25.123+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2023-11-25T19:44:05.101+0000] {job.py:219} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/jobs/job.py", line 190, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/future/engine.py", line 406, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-25T19:44:06.809+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0100 97446    0 97446    0     0  49742      0 --:--:--  0:00:01 --:--:-- 49717100 1279k    0 1279k    0     0   432k      0 --:--:--  0:00:02 --:--:--  432k100 1774k    0 1774k    0     0   437k      0 --:--:--  0:00:04 --:--:--  437k100 2414k    0 2414k    0     0   489k      0 --:--:--  0:00:04 --:--:--  489k100 2686k    0 2686k    0     0   422k      0 --:--:--  0:00:06 --:--:--  530k100 2974k    0 2974k    0     0   417k      0 --:--:--  0:00:07 --:--:--  557k100 3470k    0 3470k    0     0   434k      0 --:--:--  0:00:07 --:--:--  435k100 3870k    0 3870k    0     0   425k      0 --:--:--  0:00:09 --:--:--  416k100 4270k    0 4270k    0     0   429k      0 --:--:--  0:00:09 --:--:--  371k100 4622k    0 4622k    0     0   421k      0 --:--:--  0:00:10 --:--:--  419k100 5022k    0 5022k    0     0   413k      0 --:--:--  0:00:12 --:--:--  407k100 5422k    0 5422k    0     0   416k      0 --:--:--  0:00:13 --:--:--  388k100 5966k    0 5966k    0     0   424k      0 --:--:--  0:00:14 --:--:--  422k100 7262k    0 7262k    0     0   485k      0 --:--:--  0:00:14 --:--:--  595k100 7758k    0 7758k    0     0   477k      0 --:--:--  0:00:16 --:--:--  594k100 8142k    0 8142k    0     0   477k      0 --:--:--  0:00:17 --:--:--  638k100 8510k    0 8510k    0     0   474k      0 --:--:--  0:00:17 --:--:--  625k100 9053k    0 9053k    0     0   473k      0 --:--:--  0:00:19 --:--:--  608k100 9437k    0 9437k    0     0   468k      0 --:--:--  0:00:20 --:--:--  418k100 9693k    0 9693k    0     0   461k      0 --:--:--  0:00:20 --:--:--  407k100  9.8M    0  9.8M    0     0   459k      0 --:--:--  0:00:21 --:--:--  396k100 10.2M    0 10.2M    0     0   456k      0 --:--:--  0:00:23 --:--:--  393k100 10.3M    0 10.3M    0     0   442k      0 --:--:--  0:00:24 --:--:--  323k100 10.3M    0 10.3M    0     0   419k      0 --:--:--  0:00:25 --:--:--  229k100 10.4M    0 10.4M    0     0   403k      0 --:--:--  0:00:26 --:--:--  176k100 11.7M    0 11.7M    0     0   440k      0 --:--:--  0:00:27 --:--:--  364k100 12.0M    0 12.0M    0     0   438k      0 --:--:--  0:00:28 --:--:--  356k100 12.0M    0 12.0M    0     0   424k      0 --:--:--  0:00:29 --:--:--  335k100 12.0M    0 12.0M    0     0   398k      0 --:--:--  0:00:30 --:--:--  306k100 12.0M    0 12.0M    0     0   386k      0 --:--:--  0:00:31 --:--:--  305k100 12.0M    0 12.0M    0     0   374k      0 --:--:--  0:00:32 --:--:-- 49625100 12.0M    0 12.0M    0     0   364k      0 --:--:--  0:00:33 --:--:--  2836100 12.0M    0 12.0M    0     0   341k      0 --:--:--  0:00:36 --:--:--     0100 12.0M    0 12.0M    0     0   329k      0 --:--:--  0:00:37 --:--:--     0100 12.0M    0 12.0M    0     0   311k      0 --:--:--  0:00:39 --:--:--     0100 12.0M    0 12.0M    0     0   303k      0 --:--:--  0:00:40 --:--:--     0100 12.7M    0 12.7M    0     0   319k      0 --:--:--  0:00:40 --:--:--  105k100 19.0M    0 19.0M    0     0   467k      0 --:--:--  0:00:41 --:--:-- 1275k
[2023-11-25T19:44:06.907+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-11-25T19:44:07.733+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=extract, execution_date=20231110T000000, start_date=20231125T194324, end_date=20231125T194407
[2023-11-25T19:44:07.914+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-25T19:44:08.212+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-11-26T23:08:52.827+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=outcomes_dag/run_id=scheduled__2023-11-10T00:00:00+00:00/task_id=extract permission to 509
[2023-11-26T23:08:52.969+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=outcomes_dag/run_id=scheduled__2023-11-10T00:00:00+00:00/task_id=extract permission to 509
[2023-11-26T23:08:53.100+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.extract scheduled__2023-11-10T00:00:00+00:00 [queued]>
[2023-11-26T23:08:53.145+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.extract scheduled__2023-11-10T00:00:00+00:00 [queued]>
[2023-11-26T23:08:53.157+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-26T23:08:54.046+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract> on 2023-11-10 00:00:00+00:00
[2023-11-26T23:08:54.058+0000] {standard_task_runner.py:57} INFO - Started process 134 to run task
[2023-11-26T23:08:54.062+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'extract', 'scheduled__2023-11-10T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpnhsva878']
[2023-11-26T23:08:54.068+0000] {standard_task_runner.py:85} INFO - Job 13: Subtask extract
[2023-11-26T23:08:54.156+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=outcomes_dag/run_id=scheduled__2023-11-10T00:00:00+00:00/task_id=extract permission to 509
[2023-11-26T23:08:54.159+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.extract scheduled__2023-11-10T00:00:00+00:00 [running]> on host 613ffde293d8
[2023-11-26T23:08:54.296+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2023-11-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-10T00:00:00+00:00'
[2023-11-26T23:08:54.299+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: extract_data() missing 3 required positional arguments: 'source_url', 'gcs_bucket', and 'creds'
[2023-11-26T23:08:54.314+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=extract, execution_date=20231110T000000, start_date=20231126T230853, end_date=20231126T230854
[2023-11-26T23:08:54.339+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 13 for task extract (extract_data() missing 3 required positional arguments: 'source_url', 'gcs_bucket', and 'creds'; 134)
[2023-11-26T23:08:54.395+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-26T23:08:54.522+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
