[2023-11-26T23:12:12.981+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=outcomes_dag/run_id=manual__2023-11-26T23:11:59.850692+00:00/task_id=transform permission to 509
[2023-11-26T23:12:13.016+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=outcomes_dag/run_id=manual__2023-11-26T23:11:59.850692+00:00/task_id=transform permission to 509
[2023-11-26T23:12:13.234+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.transform manual__2023-11-26T23:11:59.850692+00:00 [queued]>
[2023-11-26T23:12:13.245+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.transform manual__2023-11-26T23:11:59.850692+00:00 [queued]>
[2023-11-26T23:12:13.246+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-26T23:12:13.261+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transform> on 2023-11-26 23:11:59.850692+00:00
[2023-11-26T23:12:13.270+0000] {standard_task_runner.py:57} INFO - Started process 238 to run task
[2023-11-26T23:12:13.273+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'transform', 'manual__2023-11-26T23:11:59.850692+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpoxgxf582']
[2023-11-26T23:12:13.275+0000] {standard_task_runner.py:85} INFO - Job 31: Subtask transform
[2023-11-26T23:12:13.333+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=outcomes_dag/run_id=manual__2023-11-26T23:11:59.850692+00:00/task_id=transform permission to 509
[2023-11-26T23:12:13.336+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.transform manual__2023-11-26T23:11:59.850692+00:00 [running]> on host 613ffde293d8
[2023-11-26T23:12:13.421+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2023-11-26T23:11:59.850692+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-26T23:11:59.850692+00:00'
[2023-11-26T23:12:13.423+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: transform_data() missing 3 required positional arguments: 'gcs_bucket', 'blob_name', and 'creds'
[2023-11-26T23:12:13.433+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=transform, execution_date=20231126T231159, start_date=20231126T231213, end_date=20231126T231213
[2023-11-26T23:12:13.446+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 31 for task transform (transform_data() missing 3 required positional arguments: 'gcs_bucket', 'blob_name', and 'creds'; 238)
[2023-11-26T23:12:13.485+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-26T23:12:13.510+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
